modLoader="javafml" #mandatory

loaderVersion="[32,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory

modId="bhc" #mandatory

version="${file.jarVersion}" #mandatory

displayName="Baubley Heart Canisters" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="http://example.com/" #optional

logoFile="examplemod.png" #optional

credits="Thanks goes to UpcraftLP who helped with original build. Also Abused_Master for helping when i bugged him." #optional

authors="Traverse_Joe" #optional

description='''
Heart Canisters for Baubles/Curios Enjoy :D
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.examplemod]] #optional

    modId="forge" #mandatory

    mandatory=true #mandatory

    versionRange="[32,)" #mandatory

    ordering="NONE"

    side="BOTH"

[[dependencies.bhc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
