
[General]
	#Starting Health of Player (Default:20)
	startingHealth = 20
	#How often do wither bones Drop? (1.0 = 100 % and 0.0 means 0%)
	boneDropRate = 0.15
	#The maximum stacksize for heart canisters, also the maximum amount of full hearts you can get per heart container type
	heartStackSize = 10
	#Allow Starting Health Tweaks
	allowStartingHealthTweaks = false

