modLoader="javafml"
loaderVersion="[31,)"
credits="Traverse_Joe"
authors="Traverse_Joe"
[[mods]]
    modId="bhc"
    version="${version}"
    displayName="Baubley Heart Canisters" #mandatory
    description='''
Baubley Heart Canisters
Increase your max life! Equip and Win! 
'''

[[dependencies.bhc]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
side="BOTH"
